# Qiyun Lab website configuration
remote_theme: mmistakes/minimal-mistakes@4.24.0
minimal_mistakes_skin: default
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

title: Qiyun Lab
subtitle: Computational Microbiomics
description: Arizona State University
url: https://qiyunlab.github.io/
locale: en-US

defaults:
  - scope:
      path: ''
      type: pages
    values:
      title: ''
      layout: single
      classes:
        - wide
        - fullwidth
